server:
  port: 9002
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
  shutdown: graceful

spring:
  jpa:
    hibernate:

  codec:
    max-in-memory-size: 500000KB

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://xykine.com/realms/AcedPayroll
#            issuer-uri: http://backend-keycloak-auth:8080/realms/Payroll
  data:
    redis:
      connect-timeout: 2s
      host: ${SPRING_REDIS_HOST:localhost}
#      host: localhost
      port: 6379
      timeout: 1s

    mongodb:
      #      uri: mongodb://admin:docker@localhost/payroll?tls=false&authSource=admin
      uri: ${ SPRING_DATA_MONGODB_URI }

admin:
  service:
#    url: http://localhost:9001/
    url: http://xykinehrs.com/
    maxBufferSize: 500000