server:
  port: 9002
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
  shutdown: graceful

spring:
  jpa:
    hibernate:

  data:
    redis:
      connect-timeout: 2s
      host: ${SPRING_REDIS_HOST:localhost}
      port: 6379
      timeout: 1s

    mongodb:
      uri: mongodb://admin:docker@localhost/admin?tls=false&authSource=admin

