server:
  port: 9002
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
  shutdown: graceful

spring:
  jpa:
    hibernate:
  profiles:
    active: QA
  codec:
    max-in-memory-size: 500000KB

  security:
    oauth2:
      resourceserver:
        jwt:
            issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://xykine.com/realms/Payroll}
  data:
    redis:
      connect-timeout: 2s
      host: ${SPRING_REDIS_HOST:localhost}
      port: 6379
      timeout: 1s

    mongodb:
      #      uri: mongodb://admin:docker@localhost/payroll?tls=false&authSource=admin
      uri: ${SPRING_DATA_MONGODB_URI}

admin:
  service:
    url: ${ADMIN_SERVICE_URL:http://localhost:9001/}
#    url: http://xykinehrs.com/
    maxBufferSize: 500000