server:
  port: 9002
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
  shutdown: graceful

spring:
  jpa:
    hibernate:

  codec:
    max-in-memory-size: 500000KB

  data:
    redis:
      connect-timeout: 2s
#      host: ${SPRING_REDIS_HOST:localhost}
      host: localhost
      port: 6379
      timeout: 1s

    mongodb:
      uri: mongodb://admin:docker@localhost/admin?tls=false&authSource=admin
#      uri: ${ SPRING_DATA_MONGODB_URI }

admin:
  service:
    url: http://localhost:8081/
    maxBufferSize: 500000
