spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    url: jdbc:postgresql://104.190.200.18:5432/payrolldb
    username: xykine
    password: Xy@1Payroll

  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s