spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s

    mongodb:
      uri : ${ SPRING_DATA_MONGODB_URI }
