server:
  port: 9002
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
  shutdown: graceful

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      connect-timeout: 2s
      host: ${SPRING_REDIS_HOST:localhost}
      port: 6379
      timeout: 1s

    mongodb:
      uri : ${ SPRING_DATA_MONGODB_URI }