spring:
  jpa:
    hibernate:

  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s

    mongodb:
      uri: mongodb://admin:docker@localhost/admin?tls=false&authSource=admin

