version: '3'
services:
  training-postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
     - POSTGRES_PASSWORD=docker
    ports:
     - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@xykine.com
      PGADMIN_DEFAULT_PASSWORD: xykine


  polar-redis:
    image: "redis:7.0"
    container_name: "xykine-redis"
    ports:
      - 6379:6379
