package com.xykine.computation.model;

import org.springframework.data.annotation.*;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.Set;

public record Employee(
        @Id
        Long employeeID,
        String firstName,
        String lastName,
        String middleName,
        String fullName,
        String employeeCode,
        String employeeExternalCode,
        Title title,
        String maritalStatus,
        Set<Address> addresses,
        String dob,
        String phone1,
        String phone2,
        String email,
        String officialEmail,
        String gender,
        IdType idType,
        String managerID,
        String isManager,
        EmployeeGroup employeeGroup,
        EmployeeSubGroup employeeSubGroup,
        Grade grade,
        Level level,
        ContractType contractType,
        String startDate,
        String endDate,
        Position position,
        Department department,
        String unitID,
        String dimensionID,
        String costCenterID,
        String currencyID,
        String pfaID,
        String bankID,
        String salaryFrequency,
        String accountType,
        String bankAccountNo,
        String wageEmployee,
        String isTaxable,
        String isActive,
        String isDirty,
        String encodedImage,
        String isDisable,
        String disableDate,
        String isMedical,
        String medicalDate,
        String locationID,
        String taxStateID,
        String taxStateName,
        String isPensionable,
        String updated,
        String changeStateID,
        BusinessUnit businessUnit,
        String bvn,
        String taxIDNo,
        String taxClass,
        String bankPaymentName,
        String sfRecord,
        int nombreDePart,
        int numberOfDaysOfUnpaidAbsence,
        int numberOfHours,
        BigDecimal basicSalary,
        BigDecimal hourlyRate,
        Band band,
        PaymentInfo paymentInfo,

        @CreatedDate
        String createdDate,

        @LastModifiedDate
        String lastModifiedDate,

        @CreatedBy
        String createdBy,

        @LastModifiedBy
        String lastModifiedBy,

        @Version
        int version
) {
    public static Employee of(
            String firstName,
            String lastName,
            String employeeCode,
            String dob,
            String email,
            String gender,
            Band band,
            String startDate,
            String endDate,
            String taxClass,
            int numberOfDaysOfUnpaidAbsence,
            int numberOfHours,
            BigDecimal basicSalary,
            BigDecimal hourlyRate,
            Department department
    ) {
        // Generate fullName from firstName and lastName
        String fullName = firstName + " " + lastName;

        // Return an instance with only the basic information provided
        return new Employee(
                null, // employeeID to be generated by the database
                firstName,
                lastName,
                null, // middleName not provided
                fullName,
                employeeCode,
                null, // employeeExternalCode not provided
                null, // titleID not provided
                null, // maritalStatus not provided
                null, // addressID not provided
                dob,
                null, // phone1 not provided
                null, // phone2 not provided
                email,
                null, // officialEmail not provided
                gender,
                null, // idTypeID not provided
                null, // managerID not provided
                null, // isManager not provided
                null, // employeeGroupID not provided
                null, // employeeSubGroupID not provided
                null, // gradeID not provided
                null, // levelID not provided
                null, // contractTypeID not provided
                startDate, // startDate not provided
                endDate, // endDate not provided
                null, // positionID not provided
                department, // departmentID not provided
                null, // unitID not provided
                null, // dimensionID not provided
                null, // costCenterID not provided
                null, // currencyID not provided
                null, // pfaID not provided
                null, // bankID not provided
                null, // salaryFrequency not provided
                null, // accountType not provided
                null, // bankAccountNo not provided
                null, // wageEmployee not provided
                null, // isTaxable not provided
                null, // isActive not provided
                null, // isDirty not provided
                null, // encodedImage not provided
                null, // isDisable not provided
                null, // disableD not provided
                null, // isMedical not provided
                null, // medicalD not provided
                null, // locationID not provided
                null, // taxStateID not provided
                null, // taxStateName not provided
                null, // isPensionable not provided
                null, // updated not provided
                null, // changeStateID not provided
                null, // businessUnitID not provided
                null, // bvn not provided
                null, // taxIDNo not provided
                taxClass, // taxClass not provided
                null, // bankPaymentName not provided
                null, // sfRecord not provided
                0, // nombreDePart not provided
                numberOfDaysOfUnpaidAbsence, // numberOfDaysOfUnpaidAbsence not provided
                numberOfHours, // numberOfHours not provided
                basicSalary, // basicSalary not provided
                hourlyRate, // hourlyRate not provided
                band, // band not provided
                null,
                null, // createdDate set to current time
                null, // lastModifiedDate not provided
                null, // createdBy set to a default value or determined by context
                null, // lastModifiedBy not provided
                0 // version set to default value
        );
    }
}
