package com.xykine.computation.model;


import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import org.springframework.data.annotation.*;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.List;
import java.util.Set;
import java.util.stream.StreamSupport;

public record Employee(
        @Id
        Long employeeID,

        @NotBlank(message = "The firstName must be defined.")
        String firstName,

        @NotBlank(message = "The lastName must be defined.")
        String lastName,

        String middleName,
        String fullName,

        @NotBlank(message = "The lastName must be defined.")
        String employeeCode,

        String employeeExternalCode,
        String title,
        String maritalStatus,

        @NotBlank(message = "The addressLine1 must be defined.")
        String addressLine1,
        String addressLine2,

        @NotBlank(message = "The city must be defined.")
        String city,

        @NotBlank(message = "The state must be defined.")
        String state,
        String lga,

        @NotBlank(message = "The postal Code must be defined.")
        String postalCode,

        @NotNull(message = "The date of birth must be defined.")
        String dob,

        @NotBlank(message = "The phone must be defined.")
        String phone1,
        String phone2,
        String email,

        @NotBlank(message = "The official email must be defined.")
        String officialEmail,

        @NotBlank(message = "The gender must be defined.")
        String gender,
        String idType,
        String managerID,
        String isManager,
        String employeeGroupID,
        String employeeSubGroupID,
        String grade,
        String level,
        String contractType,

        @NotNull(message = "The start date must be defined.")
        String startDate,

        String endDate,
        String position,
        String departmentID,
        String unitID,
        String dimensionID,
        String costCenterID,
        String currencyID,
        String pfaID,
        String bankID,
        String salaryFrequency,
        String accountType,
        String bankAccountNo,
        String wageEmployee,
        String isTaxable,
        String isActive,
        //TODO Date activated and deactived should be added
        //TODO change the isActive back to boolean
        String isDirty,
        String encodedImage,
        String isDisable,
        String disableDate,
        String isMedical,
        String medicalDate,
        String locationID,
        String taxStateID,
        String taxStateName,
        String isPensionable,
        String changeStateID,
        String businessUnitID,
        String bvn,
        String taxIDNo,
        String taxClass,
        String bankPaymentName,
        String sfRecord,
        int nombreDePart,
        BigDecimal basicSalary,
        BigDecimal hourlyRate,
        String band,
        Long paymentInfoId,
        Long employeeLockID,
        //TODO Update lock table as employee update lock scenario
        boolean isEmployeeLocked,
        Set<Allowance> allowances,

        // hasUnpaid

        @CreatedDate
        String createdDate,

        @LastModifiedDate
        String lastModifiedDate,

        @CreatedBy
        String createdBy,

        @LastModifiedBy
        String lastModifiedBy,

        @Version
        int version
) {

    public static Employee of(
            String firstName,
            String lastName,
            String employeeCode,
            String dob,
            String officialEmail,
            String gender,
            String startDate,
            String createdDate,
            String lastModifiedDate
//                Set<Allowance> allowances
    ) {
        // Generate fullName from firstName and lastName
        String fullName = firstName + " " + lastName;

        // Return an instance with only the basic information provided
        return new Employee(
                null, // employeeID to be generated by the database
                firstName,
                lastName,
                null, // middleName not provided
                fullName,
                employeeCode,
                null, // employeeExternalCode not provided
                null, // titleID not provided
                null, // maritalStatus not provided
                null,// addressLine1,
                null,// addressLine2,
                null,// city,
                null,// state,
                null,// lga,
                null,// postalCode,,
                // addressID not provided
                dob,
                null, // phone1 not provided
                null, // phone2 not provided
                null,
                officialEmail, // officialEmail not provided
                gender,
                null, // idTypeID not provided
                null, // managerID not provided
                null, // isManager not provided
                null, // employeeGroupID not provided
                null, // employeeSubGroupID not provided
                null, // gradeID not provided
                null, // levelID not provided
                null, // contractTypeID not provided
                startDate, // startDate not provided
                null, // endDate not provided
                null, // positionID not provided
                null, // departmentID not provided
                null, // unitID not provided
                null, // dimensionID not provided
                null, // costCenterID not provided
                null, // currencyID not provided
                null, // pfaID not provided
                null, // bankID not provided
                null, // salaryFrequency not provided
                null, // accountType not provided
                null, // bankAccountNo not provided
                null, // wageEmployee not provided
                null, // isTaxable not provided
                null, // isActive not provided
                null, // isDirty not provided
                null, // encodedImage not provided
                null, // isDisable not provided
                null, // disableD not provided
                null, // isMedical not provided
                null, // medicalD not provided
                null, // locationID not provided
                null, // taxStateID not provided
                null, // taxStateName not provided
                null, // isPensionable not provided
                null, // changeStateID not provided
                null, // businessUnitID not provided
                null, // bvn not provided
                null, // taxIDNo not provided
                null, // taxClass not provided
                null, // bankPaymentName not provided
                null, // sfRecord not provided
                0, // nombreDePart not provided
                null, // basicSalary not provided
                null, // hourlyRate not provided
                null, // band not provided
                null,
                null,
                false,
                null,
                // lastModifiedBy not provided
                createdDate, // createdDate set to current time
                lastModifiedDate, // lastModifiedDate not provided
                "test User", // createdBy set to a default value or determined by context
                "test User", // lastModifiedBy not provided
                0 // version set to default value
        );
    }
}