name: Build and Test

on:
  workflow_dispatch:
    inputs:
      image_version:
        description: 'Docker image version (if manual override needed)'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_OWNER: "xykineltd"  # Replace with your GitHub organization or username
      PACKAGE_NAME: "org.xykine.payroll.payment-settings-model"

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Set up Maven settings
      - name: Set up Maven settings with PAT for GitHub Packages
        env:
          PAT_TOKEN: ${{ secrets.GH_PAT_TOKEN }}
        run: |
          mkdir -p ~/.m2
          echo "<settings>
                  <servers>
                    <server>
                      <id>github</id>
                      <username>${{ github.actor }}</username>
                      <password>${PAT_TOKEN}</password>
                    </server>
                  </servers>
                 </settings>" > ~/.m2/settings.xml

      # Step 4: Fetch the latest Docker image version from Docker Hub and increment it
      - name: Fetch and increment Docker image version
        id: version
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          repo_name="kacytunde/paycomputation-service"
          latest_version=$(curl -s -u "${DOCKER_USERNAME}:${{ secrets.DOCKER_PASSWORD }}" \
            "https://hub.docker.com/v2/repositories/${repo_name}/tags?page_size=1" \
            | jq -r '.results[0].name')

          echo "Latest version from Docker Hub: $latest_version"

          # Extract major and minor version
          major=$(echo $latest_version | cut -d '.' -f 1)
          minor=$(echo $latest_version | cut -d '.' -f 2)

          # Increment minor version, roll over major if needed
          if [ "$minor" -ge 9 ]; then
            new_major=$((major + 1))
            new_minor=0
          else
            new_major=$major
            new_minor=$((minor + 1))
          fi

          # Construct new version
          new_version="$new_major.$new_minor"
          echo "New version: $new_version"

          # Use input image_version if provided
          if [ "${{ github.event.inputs.image_version }}" != "" ]; then
            new_version="${{ github.event.inputs.image_version }}"
          fi

          echo "Final image version: $new_version"
          echo "image_version=$new_version" >> $GITHUB_ENV

      # Step 5: Log the new version
      - name: Log Docker Image Version
        run: |
          echo "Docker image version to be used: ${{ env.image_version }}"

      # Step 6: Build and push Docker image
      - name: Build and Push Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_VERSION: ${{ env.image_version }}
        run: |
          mvn -Dmaven.test.skip spring-boot:build-image \
          -Ddocker.publishRegistry.username=${DOCKER_USERNAME} \
          -Ddocker.publishRegistry.password=${DOCKER_PASSWORD} \
          -Ddocker.publishRegistry.url=docker.io \
          -Dspring-boot.build-image.publish=true \
          -Dspring-boot.build-image.imageName=kacytunde/paycomputation-service:${IMAGE_VERSION}